repos:
  - repo: https://github.com/omnilib/ufmt
    rev: v2.7.3
    hooks:
      - id: ufmt
        additional_dependencies:
          - black == 24.8.0
          - usort == 1.0.8.post1
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies:
          - "flake8-pyproject"
          - flake8-docstrings
          - pydocstyle
