name: Test judge0-py

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
          pipenv install -e .
      - name: Test with pytest
        env: # Add necessary api keys as env variables.
          ATD_API_KEY: ${{ secrets.ATD_API_KEY }}
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
          SULU_API_KEY: ${{ secrets.SULU_API_KEY }}
        run: |
          pipenv run pytest -vv
