name: Test judge0-python

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
          pipenv install -e .
      - name: Test with pytest
        env: # Add necessary api keys as env variables.
          JUDGE0_ATD_API_KEY: ${{ secrets.JUDGE0_ATD_API_KEY }}
          JUDGE0_RAPID_API_KEY: ${{ secrets.JUDGE0_RAPID_API_KEY }}
          JUDGE0_SULU_API_KEY: ${{ secrets.JUDGE0_SULU_API_KEY }}
          JUDGE0_TEST_API_KEY: ${{ secrets.JUDGE0_TEST_API_KEY }}
          JUDGE0_TEST_API_KEY_HEADER: ${{ secrets.JUDGE0_TEST_API_KEY_HEADER }}
          JUDGE0_TEST_CE_ENDPOINT: ${{ secrets.JUDGE0_TEST_CE_ENDPOINT }}
          JUDGE0_TEST_EXTRA_CE_ENDPOINT: ${{ secrets.JUDGE0_TEST_EXTRA_CE_ENDPOINT }}
        run: |
          pipenv run pytest -vv tests/
